### ISSUE TITLE
How to connect to px4?

### ISSUE THREAD

**Issue by seungbeom-son** [Dronecode/DronecodeSDK-Swift-Example#28]
I' using px4 with hex cube black (https://docs.px4.io/master/en/flight_controller/pixhawk-2.html) and herelink (https://docs.cubepilot.org/user-guides/herelink/herelink-overview).

When I installed QGroundControl from App store, my iOS device could connect to px4 via QGroundControl.

But, I could not connect to the px4 with this sample app in the same circumstance.

Is there anything I should set before connecting? Or doesn't MAVSDK support px4 with hex cube black or herelink?

**Comment by julianoes** [comment]
Can you share exactly your hardware setup and your connection settings that you use?

**Comment by seungbeom-son** [comment]
> Can you share exactly your hardware setup and your connection settings that you use?

All of the devices I have are pixhawk2, cube, herelink(RC), iPad.

I connected UART of herelink to Telemetry1 of pixhawk, SBUS of herelink to RCIN of pixhawk.

And, I turned on mobile hotspot of herelink and connected my iPad to the AP via wifi.

These are my connection settings.

(I'm sorry about my poor description. If you want more detailed explanation, please ask me again. Thank you)

**Comment by hamishwillee** [comment]
FWIW PX4 works with Cube black - that is Pixhawk-compatible. 

@seungbeom-son

I don't understand your setup; are you saying that MAVSDK-Swift is running on the iPad and you think that by connecting to HERELINK API the mavlink traffic will be redirect to PX4?

Further, what Julian means by "connection" settings, is probably "what ports" are you connecting to in your code - ie the stuff here: http://dronecode-sdk-swift.s3.eu-central-1.amazonaws.com/docs/master/index.html

**Comment by seungbeom-son** [comment]
@hamishwillee 

> I don't understand your setup; are you saying that MAVSDK-Swift is running on the iPad and you think that by connecting to HERELINK API the mavlink traffic will be redirect to PX4?

Yes, MAVSDK-Swift is running on my iPad. And I think that by connecting to HERELINK API, the mavlink traffic will be redirect to PX4 because QGroundControl app running on the iPad could redirect to PX4 in the same way.

> Further, what Julian means by "connection" settings, is probably "what ports" are you connecting to in your code - ie the stuff here: http://dronecode-sdk-swift.s3.eu-central-1.amazonaws.com/docs/master/index.html

I connected to default port (14540)

**Comment by Tao-pai-pai** [comment]
I have the exactly same issue.

I need to connect my ipad to pixhawk through herelink.
(I have to take my drone off in real world, not in simulation world. In this case, my drone may not be able to connect to ethernet because it may fly in some remote areas. So, I need other channels to connect my ipad to pixhawk (ex.herelink))

With QGroundControl installed from app store, I could connect my ipad to pixhawk via herelink.

Although QGroundControl works well, I should develop my own app instead of QGroundControl. But, I wonder how to 

achieve this.

Please help me.

**Comment by julianoes** [comment]
I assume this has been resolved in the meantime, and I'm closing this issue.
