### ISSUE TITLE
How to use Offboard API?

### ISSUE THREAD

**Issue by LittleShengApp** [Dronecode/DronecodeSDK-Swift-Example#30]
Thanks for great example source code!
I can running app on iPad, and connect to PX4 SITL on jMAVSim.

I call the Action API successfully
(Arm, Takeoff, Landing, Disarm),
but call Offboard API failed
(Call setAttitude(attitude:) successfully first, then call start() got failed).

How to correct use Offboard API?
Sorry for my poor English.

**Comment by julianoes** [comment]
Was there any error? What was the result of `start()`?

**Comment by LittleShengApp** [comment]
I got the error: 
Unhandled error happened: OffboardError(code: MAVSDK_Swift.Offboard.OffboardResult.Result.noSetpointSet, description: "No Setpoint Set")

The test flow as follow:
1. call action.arm() 
    -> Drone arm successfully.
2. call action.takoff() 
    -> Drone takeoff succseesully (Using minimum takeoff altitude: 2.50 m (system_impl.cpp:230)).
3. call offboard.setAttitude(attitude: Offboard.Attitude(rollDeg: 0.0, pitchDeg: 0.0, yawDeg: 30.0, thrustValue: 0.0)) 
    -> No error & onCompleted.
4. call offboard.start() 
    -> Unhandled error happened: OffboardError(code: MAVSDK_Swift.Offboard.OffboardResult.Result.noSetpointSet, description: "No Setpoint Set")

I use offboard API correctly or not?
What is Setpoint Set?

Thanks.

**Comment by julianoes** [comment]
That all looks correct. That's odd. Is there a sleep between 3. and 4.?

**Comment by LittleShengApp** [comment]
Yes, I create two buttons for 3. and 4.

What does Setpoint Set mean?
Does MAVSDK-swift have any API to set flight mode of PX4 SITL from "Hold" to "Offboard"?

**Comment by julianoes** [comment]
Aha, if you have two buttons then you need to press them quite quickly, I think within 3 seconds (depending on the version), so I would suggest to combine it within one button.

**Comment by julianoes** [comment]
>  from "Hold" to "Offboard"?

That's what `start_offboard()` does.

**Comment by LittleShengApp** [comment]
@julianoes 
You give an important hint for me! It works!
Thanks a lot!! :D

Now I encounter another problem.
For example when I use offboard.setPositionNed(positionNedYaw: Offboard.PositionNedYaw(northM: 0.0, eastM: 0.0, downM: -10.0, yawDeg: 0.0)),
the drone will fly to destination, 
and jMAVSim always show "WARN  [mc_pos_control] invalid setpoints".

Does it matter?
I use wrong or unsafe parameters for offboard API?

**Comment by julianoes** [comment]
> "WARN [mc_pos_control] invalid setpoints".

Hm, that's odd. I will try to reproduce that.

I don't know if it matters or is not safe.

What version of PX4 are you using?

**Comment by LittleShengApp** [comment]
My PX4 version is v1.11.0-rc3-1021-g6c9072720e.

**Comment by julianoes** [comment]
Ok, I'll try to reproduce this. Either this or next week.

**Comment by julianoes** [comment]
This warning should get fixed with https://github.com/PX4/PX4-Autopilot/pull/17725.
