### ISSUE TITLE
Problem flying missions

### ISSUE THREAD

**Issue by sbporter** [Dronecode/DronecodeSDK-Swift-Example#8]
I'm having issues with takeoff and flying missions. 
- Arming/Disarming consistently works
- Take Off seems to work only 1/3 of the time. The other times it will just stay armed and then disarm itself after a few seconds. Each time it fails, the message in red reads "Takeoff succeeded".
- Mission upload always fails with the error: "Mission upload failed MissionError(code: Dronecode..."
- Mission start fails most of the time with the error: "Mission start failed MissionError(code: Dronecode_S..."
- When mission start does work, the drone takes off hovers for 5 seconds or so, and then lands.

<img width="706" alt="Screen Shot 2019-03-26 at 9 16 12 PM" src="https://user-images.githubusercontent.com/13425293/55048050-683a6d80-500c-11e9-85ad-fbf8c2009a04.png">
<img width="708" alt="Screen Shot 2019-03-26 at 9 15 18 PM" src="https://user-images.githubusercontent.com/13425293/55048033-522cad00-500c-11e9-9445-41969afb8bb1.png">

**Comment by julianoes** [comment]
Thanks for the report. Do you also get output in XCode, that would be very helpful in finding what's going on.

**Comment by sbporter** [comment]
I didn’t have the debugger attached as I was at the park. I’ll retest and make sure I save the logs. The mission feature in the example app is complete and should function as intended right? You haven’t seen this issue?

**Comment by julianoes** [comment]
Right, this has worked before, so it's either something with your setup or a regression. You can also test this against SITL or HITL to save trips to the park.

**Comment by sbporter** [comment]
So looks like I need a MicroSD. I'm pretty sure my drone doesn't have one attached to the PX4. I will close the issue.
```Create flight path at  (40.3936, -111.8948)
Upload Mission Pressed
[03:50:48|Debug] Send mission item 0 (mission_impl.cpp:1088)
[03:50:48|Error] Error: unknown mission ack: 1 (mission_impl.cpp:165)
[03:50:48|Debug] MAVLink: critical: Unable to write on micro SD (system_impl.cpp:292)
Mission uploaded failed MissionError(code: Dronecode_SDK_Swift.Mission.MissionResult.Result.error, description: "Error")```
